version: '3.8'

services:
  return:
    build:
      context: .
      dockerfile: return.Dockerfile
    ports:
      - "5011:5011"
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
