# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geofence.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egeofence.proto\x12\x08geofence\"\xa9\x01\n\x03\x43\x61r\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04make\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\x05\x12\r\n\x05\x63olor\x18\x05 \x01(\t\x12\x16\n\x0eprice_per_hour\x18\x06 \x01(\x01\x12\x11\n\tavailable\x18\x07 \x01(\x08\x12\x10\n\x08latitude\x18\x08 \x01(\x01\x12\x11\n\tlongitude\x18\t \x01(\x01\x12\x0c\n\x04town\x18\n \x01(\t\"R\n\x0fGeofenceRequest\x12\x15\n\ruser_latitude\x18\x01 \x01(\x01\x12\x16\n\x0euser_longitude\x18\x02 \x01(\x01\x12\x10\n\x08location\x18\x03 \x01(\t\"&\n\x07\x43\x61rList\x12\x1b\n\x04\x63\x61rs\x18\x01 \x03(\x0b\x32\r.geofence.Car2\x97\x01\n\x0fGeofenceService\x12\x41\n\x11GetCarsInGeofence\x12\x19.geofence.GeofenceRequest\x1a\x11.geofence.CarList\x12\x41\n\x11GetCarsInLocation\x12\x19.geofence.GeofenceRequest\x1a\x11.geofence.CarListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geofence_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAR._serialized_start=29
  _CAR._serialized_end=198
  _GEOFENCEREQUEST._serialized_start=200
  _GEOFENCEREQUEST._serialized_end=282
  _CARLIST._serialized_start=284
  _CARLIST._serialized_end=322
  _GEOFENCESERVICE._serialized_start=325
  _GEOFENCESERVICE._serialized_end=476
# @@protoc_insertion_point(module_scope)
