# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import geofence_pb2 as geofence__pb2


class GeofenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCarsInGeofence = channel.unary_unary(
                '/geofence.GeofenceService/GetCarsInGeofence',
                request_serializer=geofence__pb2.GeofenceRequest.SerializeToString,
                response_deserializer=geofence__pb2.CarList.FromString,
                )
        self.GetCarsInLocation = channel.unary_unary(
                '/geofence.GeofenceService/GetCarsInLocation',
                request_serializer=geofence__pb2.GeofenceRequest.SerializeToString,
                response_deserializer=geofence__pb2.CarList.FromString,
                )


class GeofenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCarsInGeofence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCarsInLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeofenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCarsInGeofence': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarsInGeofence,
                    request_deserializer=geofence__pb2.GeofenceRequest.FromString,
                    response_serializer=geofence__pb2.CarList.SerializeToString,
            ),
            'GetCarsInLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCarsInLocation,
                    request_deserializer=geofence__pb2.GeofenceRequest.FromString,
                    response_serializer=geofence__pb2.CarList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'geofence.GeofenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GeofenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCarsInGeofence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geofence.GeofenceService/GetCarsInGeofence',
            geofence__pb2.GeofenceRequest.SerializeToString,
            geofence__pb2.CarList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCarsInLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/geofence.GeofenceService/GetCarsInLocation',
            geofence__pb2.GeofenceRequest.SerializeToString,
            geofence__pb2.CarList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
