version: '3.8'

services:
  aiprocessing:
    build:
      context: .
      dockerfile: aiprocessing.Dockerfile
    environment:
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
    networks:
      - flask-network

networks:
  flask-network:
    driver: bridge
